export const MEDICAL_RECORD_TYPES = {
    GENERAL: 1,
    ORAL_PROSTHESIS: 2,
    PERIODONTICS: 3,
    DENTAL_OPERATION: 4,
    ORAL_SURGERY: 5,
    PREVENTIVE_DENTISTRY: 6,
    ENDODONTIC: 7,
    PULPOTOMY: 8,
    PULPECTOMY: 9,
    DENTAL_OPERATION_PREVIO: 10,
} as const;