export * from './components/base/base.component';
export * from './components/button-menu-item/button-menu-item.component';
export * from './components/footer/footer.component';
export * from './components/header/header.component';
export * from './components/side-nav/side-nav.component';
export * from './interfaces/tabs_handler'
export * from './components/loading/loading.component';
export * from './components/tabla-data/tabla-data.component';
export * from './interfaces/student/student'
export * from './pipes/array-to-date.pipe'