export * from './components/layout/students-layout.component';
export * from './components/table-patients/students-patients.component';
export * from './components/odontogram/students-odontogram.component';
export * from './components/toolbar-odontogram/students-toolbar.component'
export * from './components/tooth/students-tooth.component';
export * from './adapters/odontogram';
export * from './components/odontogram-list/odontogram-list.component';
export * from './components/card-patient-data/card-patient-data.component';
export * from './components/dialog-confirm-send-to-review/dialog-confirm-send-to-review.component';
export * from './components/dialog-new-treatment/dialog-new-treatment.component';
export * from './pages/medicalRecords/dental-operation/students-dental-operation.component';
export * from './pages/medicalRecords/general/students-general-history.component';
export * from './pages/medicalRecords/oral-prosthesis/oral-prosthesis.component';
export * from './pages/medicalRecords/oral-surgery/students-oral-surgery-history.component';
export * from './pages/medicalRecords/periodontics/students-periodontics-history.component';
export * from './pages/medicalRecords/preventive-dentistry-public-health/preventive-dentistry-public-health.component';
export * from './components/form-update-patient/form-update-patient.component';
export * from './components/socket-notifications/services/medical-record-ws.service';
export * from './components/socket-notifications/services/treatments-notifications-ws.service';
export * from './components/socket-notifications/components/treatments-notifications.component'