export const ROLES = {
  ADMIN: 'ROLE_ADMIN',
  PROFESSOR: 'ROLE_PROFESSOR',
  STUDENT: 'ROLE_STUDENT',
  CLINICAL_AREA_SUPERVISOR : 'ROLE_CLINICAL_AREA_SUPERVISOR', 
  ROLE_MEDICAL_RECORD_DIGITIZER : 'ROLE_MEDICAL_RECORD_DIGITIZER',
  RECORD_DIGITIZER: 'ROLE_RECORD_DIGITIZER'
};