export const STATUS = {
    NO_STATUS: 'NO_STATUS',
    NO_REQUIRED: 'NO_REQUIRED',
    IN_REVIEW: 'IN_REVIEW',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    NOT_REQUIRED: 'NOT_REQUIRED'
};  

export const STATUS_TREATMENTS = {
    IN_REVIEW: 'IN_REVIEW',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    IN_PROGRESS: 'IN_PROGRESS',
    FINISHED: 'FINISHED',
    CANCELLED: 'CANCELLED',
};